=== api-evangelist/amazon-interactive-video-service/json-schema/ivs-update-channel-request-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-interactive-video-service/refs/heads/main/json-schema/ivs-update-channel-request-schema.json",
  "title": "UpdateChannelRequest",
  "description": "UpdateChannelRequest schema",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChannelArn"
        },
        {
          "description": "ARN of the channel to be updated."
        }
      ]
    },
    "authorized": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Whether the channel is private (enabled for playback authorization)."
        }
      ]
    },
    "insecureIngest": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Boolean"
        },
        {
          "description": "Whether the channel allows insecure RTMP ingest. Default: <code>false</code>."
        }
      ]
    },
    "latencyMode": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChannelLatencyMode"
        },
        {
          "description": "Channel latency mode. Use <code>NORMAL</code> to broadcast and deliver live video up to Full HD. Use <code>LOW</code> for near-real-time interaction with viewers. (Note: In the Amazon IVS console, <code>LOW</code> and <code>NORMAL</code> correspond to Ultra-low and Standard, respectively.)"
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChannelName"
        },
        {
          "description": "Channel name."
        }
      ]
    },
    "preset": {
      "allOf": [
        {
          "$ref": "#/components/schemas/TranscodePreset"
        },
        {
          "description": "Optional transcode preset for the channel. This is selectable only for <code>ADVANCED_HD</code> and <code>ADVANCED_SD</code> channel types. For those channel types, the default <code>preset</code> is <code>HIGHER_BANDWIDTH_DELIVERY</code>. For other channel types (<code>BASIC</code> and <code>STANDARD</code>), <code>preset</code> is the empty string (<code>\"\"</code>)."
        }
      ]
    },
    "recordingConfigurationArn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChannelRecordingConfigurationArn"
        },
        {
          "description": "Recording-configuration ARN. If this is set to an empty string, recording is disabled. A value other than an empty string indicates that recording is enabled"
        }
      ]
    },
    "type": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ChannelType"
        },
        {
          "description": "<p>Channel type, which determines the allowable resolution and bitrate. <i>If you exceed the allowable input resolution or bitrate, the stream probably will disconnect immediately.</i> Some types generate multiple qualities (renditions) from the original input; this automatically gives viewers the best experience for their devices and network conditions. Some types provide transcoded video; transcoding allows higher playback quality across a range of download speeds. Default: <code>STANDARD</code>. Valid values:</p> <ul> <li> <p> <code>BASIC</code>: Video is transmuxed: Amazon IVS delivers the original input quality to viewers. The viewer\u2019s video-quality choice is limited to the original input. Input resolution can be up to 1080p and bitrate can be up to 1.5 Mbps for 480p and up to 3.5 Mbps for resolutions between 480p and 1080p. Original audio is passed through.</p> </li> <li> <p> <code>STANDARD</code>: Video is transcoded: multiple qualities are generated from the original input, to automatically give viewers the best experience for their devices and network conditions. Transcoding allows higher playback quality across a range of download speeds. Resolution can be up to 1080p and bitrate can be up to 8.5 Mbps. Audio is transcoded only for renditions 360p and below; above that, audio is passed through. This is the default when you create a channel.</p> </li> <li> <p> <code>ADVANCED_SD</code>: Video is transcoded; multiple qualities are generated from the original input, to automatically give viewers the best experience for their devices and network conditions. Input resolution can be up to 1080p and bitrate can be up to 8.5 Mbps; output is capped at SD quality (480p). You can select an optional transcode preset (see below). Audio for all renditions is transcoded, and an audio-only rendition is available.</p> </li> <li> <p> <code>ADVANCED_HD</code>: Video is transcoded; multiple qualities are generated from the original input, to automatically give viewers the best experience for their devices and network conditions. Input resolution can be up to 1080p and bitrate can be up to 8.5 Mbps; output is capped at HD quality (720p). You can select an optional transcode preset (see below). Audio for all renditions is transcoded, and an audio-only rendition is available.</p> </li> </ul> <p>Optional <i>transcode presets</i> (available for the <code>ADVANCED</code> types) allow you to trade off available download bandwidth and video quality, to optimize the viewing experience. There are two presets:</p> <ul> <li> <p> <i>Constrained bandwidth delivery</i> uses a lower bitrate for each quality level. Use it if you have low download bandwidth and/or simple video content (e.g., talking heads)</p> </li> <li> <p> <i>Higher bandwidth delivery</i> uses a higher bitrate for each quality level. Use it if you have high download bandwidth and/or complex video content (e.g., flashes and quick scene changes).</p> </li> </ul>"
        }
      ]
    }
  },
  "required": [
    "arn"
  ]
}

=== api-evangelist/amazon-interactive-video-service/examples/ivs-update-channel-request-example.json
{
  "arn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "authorized": "example-value",
  "insecureIngest": "example-value",
  "latencyMode": "example-value",
  "name": "example-resource",
  "preset": "example-value",
  "recordingConfigurationArn": "arn:aws:iot:us-east-1:123456789012:thing/example",
  "type": "example-value"
}
